In [1]:
import math

def sigmoid(x):
    return 1/(1+math.exp(-x))


In [2]:
sigmoid(100)


1.0

In [3]:
sigmoid(1)

0.7310585786300049

In [4]:
sigmoid(-56)

4.780892883885469e-25

In [5]:
sigmoid(0.5)

0.6224593312018546

In [7]:
def tanh(x):
    return (math.exp(x) - math.exp(-x))/(math.exp(x) + math.exp(-x))

In [8]:
tanh(100)

1.0

In [9]:
def relu(x):
    return max(0,x)

In [10]:
relu(-4)

0

In [11]:
relu(5)

5

In [12]:
def leaky_relu(x):
    return max(0.1*x,x)

In [13]:
leaky_relu(5)

5

In [14]:
leaky_relu(-6)

-0.6000000000000001

In [16]:
leaky_relu(-100)

-10.0

In [17]:
import numpy as np
revenue = np.array([[180,200,220],[26,34,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])
                   

In [18]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 16,  18,  20],
       [  4,   8,  10]])

In [19]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [20]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [22]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])